### ISSUE TITLE
Plotting Inconsistencies

### ISSUE THREAD

**Issue by jenniferyee** [rpoleski/MulensModel#1]
There are various inconsistencies with the plotting methods in the development branch:

mulensdata.plot()
model.plot_data()
model.plot_residuals()

The desired behavior is that all three of these functions works the same way except that they plot slightly different things. Therefore, there should be a common set of arguments between them. As with the event.plot_data() method, that common set should be passed with **kwargs so they can be maintained in some centralized location. The methods also need to take **kwargs for plotting. 

Our special kwargs:
  subtract_2450000, subtract_2460000
  show_errorbars, show_bad

They all need to be able to access MulensData.plot_properties().

I think this means that we need a common "plot(t, x, **kwargs)" function for all of them.

**Comment by rpoleski** [comment]
I have thought more about the plotting and I don't see any major issue with the changes I've started (except it's not yet coded). **Please let me know if you see some major obstacles** and I'll try to address them. Below, I explain details of implementation.

Model functions that call Fit() should remember it. As of now, I've added 2 arguments to MulensData.plot(): model and fit. If Model remembers Fit(), then we'll be adding just one argument to MulensData.plot(), i.e., model.

MulensData.plot() needs information from Model in order to plot given dataset in brightness space from other dataset. 

Model.get_residuals() currently calculates residuals for all datasets, but can be modified so that it works on a single dataset. This way we could allow MulensData.plot() to plot residuals of given model. User would need to provide model and set a keyword, e.g., plot_residuals=True (default: False). Both Model.plot_data() and Model.plot_residuals() will be relatively short and their main task would be to call MulensData.plot() for each dataset.

**Comment by rpoleski** [comment]
Development branch with all the changes was merged. UC27 works as expected, example 5 works as expected.
