### ISSUE TITLE
Pyplot interactive output figure needed

### ISSUE THREAD

**Issue by wyrzykow** [rpoleski/MulensModel#140]
Interactive plot as an output figure from modelling is needed. We use MulensModel in BHTOM service (http://bhtom.space) for quick-look models and it would be useful to interact with the output figure, both in the light curve and residuals. 
![image](https://github.com/rpoleski/MulensModel/assets/26644157/c3cdac9a-27b0-40b6-88ba-3914b4af0b4a)

**Comment by rpoleski** [comment]
I would say there are 2 approaches:

1. Allow plotly instead of pyplot in various plotting functions in MM.
2. Just make an example that calls: `Model.get_lc()`, `Event.fits[].scale_fluxes()`, and `Event.fits[].get_residuals()` to calculate model, scaled datasets, and residuals, respectively.

First one will be definitely more time-consuming to implement. Any comments?

**Comment by rpoleski** [comment]
@mjmroz, do you have an example that you could share?

**Comment by mjmroz** [comment]
Of course, I have Plotly codes for everything: light curve with residuals and cumulative chi2, trajectory, and even some animations of both :) .
I wrote them gradually, so they are a bit messy, but I can prepare a clean example in free time. 
I can also work on allowing Plotly in MM or build an additional visualization tool with more options than currently available in MM.

**Comment by rpoleski** [comment]
@mjmroz Please add a simple plot of a data and model in one subplot and residuals in another subplot.

**Comment by rpoleski** [comment]
It's already implemented in example 16. Closing.
