### ISSUE TITLE
Zero Blending Flux Inconsistent

### ISSUE THREAD

**Issue by jenniferyee** [rpoleski/MulensModel#4]
1. While there is a fit_blending parameter for event.get_chi2() and event.get_chi2_for_dataset(), there is no fit_blending parameter for event.plot_model() or get_ref_fluxes(). Thus, there is no way to fix the blending=0 when plotting a model.

2. There should be a way to fix the blending parameters separately for different datasets and to values other than zero.

**Comment by rpoleski** [comment]
While MM is lacking options you mention, there are relatively easy ways to overcome the problems:

- For event.plot_model(), you can use f_source and f_blend keywords to directly provide fluxes you want. To get the source flux for no-blending approach, the easiest hack is to call Event.get_chi2(fit_blending=False) and then access Event.fit.flux_of_sources().
- Instead of get_ref_fluxes() you can use the hack from point above.
- If you want fix blending separately to calculate chi2, then use Event.get_chi2_for_dataset(..., fit_blending=...).

Fixing flux for non-zero values would require a use case. Other things are already on "to do" list - I'll move them up in hierarchy. 

It was already recognized that fit_blending is somehow problematic in current implementation. The idea for future (MM v2) is to make it MulensData property instead of a parameter in a number of functions in different classes.

**Comment by rpoleski** [comment]
The get_ref_fluxes() issue was solved in commit ca42430. The Event.plot_model() seems easy to fix, but I'd like to test it first.

Version 1.11.0 will soon be linked on main website.

**Comment by rpoleski** [comment]
@jenniferyee, your point 1. is now fully solved. Last changes are [here](https://github.com/rpoleski/MulensModel/commit/48a7b1ec9469d77c0153dda68fbc047954e04b45#diff-443f5c935ea6df711959bafcd3323783).

Point 2. is not done and requires use cases.

**Comment by jenniferyee** [comment]
Great! I will think more about use cases.

- Jennifer

--------------------------------------------------------------
Dr. Jennifer C. Yee

Office: P-341
Harvard-Smithsonian Center for Astrophysics
60 Garden St, MS-15
Cambridge, MA 02138
--------------------------------------------------------------

**Comment by jenniferyee** [comment]
This issue was resolved with Version 2.
